package l2j.gameserver.model.actor.manager.character.skills.enums;

/**
 * @author fissban
 */
public enum SkillTargetType
{
	TARGET_NONE,
	TARGET_SELF,
	TARGET_ONE,
	TARGET_PARTY,
	TARGET_ALLY,
	TARGET_CLAN,
	TARGET_PET,
	TARGET_AREA,
	TARGET_AURA,
	TARGET_CORPSE,
	TARGET_UNDEAD,
	TARGET_AURA_UNDEAD,
	TARGET_FRONT_AREA,
	TARGET_CORPSE_ALLY,
	TARGET_CORPSE_PLAYER,
	TARGET_CORPSE_PET,
	TARGET_ITEM,
	TARGET_AREA_CORPSE_MOB,
	TARGET_CORPSE_MOB,
	TARGET_MOB,
	TARGET_UNLOCKABLE,
	TARGET_HOLY,
	TARGET_PARTY_MEMBER,
	TARGET_OWNER_PET
}
