DROP TABLE IF EXISTS `custom_weapon`;
CREATE TABLE `custom_weapon` (
  `item_id` int(11) NOT NULL DEFAULT 0,
  `name` varchar(70) DEFAULT NULL,
  `bodypart` enum('hatchling','lhand','lrhand','rhand','strider','wolf') DEFAULT NULL,
  `crystallizable` enum('true','false') DEFAULT 'true',
  `weight` int(4) DEFAULT NULL,
  `soulshots` tinyint(2) DEFAULT NULL,
  `spiritshots` tinyint(2) DEFAULT NULL,
  `material` varchar(11) DEFAULT NULL,
  `crystal_type` enum('none','d','c','b','a','s') DEFAULT 'none',
  `p_dam` int(5) DEFAULT NULL,
  `rnd_dam` tinyint(2) DEFAULT NULL,
  `weaponType` varchar(8) DEFAULT NULL,
  `critical` int DEFAULT NULL,
  `hit_modify` int(6) DEFAULT NULL,
  `avoid_modify` int DEFAULT NULL,
  `shield_def` int(3) DEFAULT NULL,
  `shield_def_rate` int DEFAULT NULL,
  `atk_speed` int(3) DEFAULT NULL,
  `mp_consume` int DEFAULT NULL,
  `m_dam` int(3) DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `crystal_count` int(4) DEFAULT NULL,
  `sellable` enum('true','false') DEFAULT 'true',
  `dropable` enum('true','false') DEFAULT 'true',
  `destroyable` enum('true','false') DEFAULT 'true',
  `tradeable` enum('true','false') DEFAULT 'true',
  `item_skill_id` int(11) NOT NULL DEFAULT 0,
  `item_skill_lvl` int(11) NOT NULL DEFAULT 0,
  `onCast_skill_id` int(11) NOT NULL DEFAULT 0,
  `onCast_skill_lvl` int(11) NOT NULL DEFAULT 0,
  `onCast_skill_chance` int(11) NOT NULL DEFAULT 0,
  `onCrit_skill_id` int(11) NOT NULL DEFAULT 0,
  `onCrit_skill_lvl` int(11) NOT NULL DEFAULT 0,
  `onCrit_skill_chance` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`item_id`)
);